%USER true for parallel processing

%How to create blobs from raw data:
start_blob_batch_user_training(...
    '/Users/afischer/Documents/MATLAB/SantaCruz/IFCB_data/IFCB104/data/2016/',...
    '/Users/afischer/Documents/MATLAB/SantaCruz/IFCB_products/IFCB104/blobs/blobs2016/',true)

%%
%How to create features from raw data:
start_feature_batch_user_training(...
    '/Users/afischer/Documents/MATLAB/SantaCruz/IFCB_data/IFCB104/data/2016/',...
    '/Users/afischer/Documents/MATLAB/SantaCruz/IFCB_products/IFCB104/blobs/blobs2016/',...
    '/Users/afischer/Documents/MATLAB/SantaCruz/IFCB_products/IFCB104/features/features2016/',true)
