function [ ind_out, class_label ] = get_cell_ind_CA( class2use, class_label )
%function [ ind_out, class_label ] = get_cell_ind( class2use, class_label )
% California class list specific to return of indices that correspond to 
% living taxa
%  Alexis D. Fischer, University of California - Santa Cruz, June 2018

class2get = {'Akashiwo' 'Alexandrium_singlet' 'Amy_Gony_Protoc' 'Ceratium'...
    'Cochlodinium' 'DinoMix' 'Dinophysis' 'Gymnodinium' 'Gyrodinium' 'Karenia'...
    'Lingulodinium' 'Noctiluca' 'Polykrikos' 'Prorocentrum' 'Protoperidinium'...
    'Pyrocystis' 'Scrip_Het' 'Boreadinium' 'Azadinium' 'Torodinium' 'Oxyp_Oxyt'...
    'Asterionellopsis' 'Bacteriastrum' 'Boreadinium' 'Centric'...
    'Chaetoceros' 'Corethron' 'Cyl_Nitz' 'Det_Cer_Lau' 'Ditylum' 'Entomoneis'...
    'Eucampia' 'Guin_Dact' 'Gyrosigma' 'Hemiaulus' 'Helicotheca' 'Lio_Thal'...
    'Leptocylindrus' 'Licmophora' 'Lithodesmium' 'Odontella' 'Paralia' 'Pennate'...
    'Pleurosigma' 'Pseudo-nitzschia' 'Rhiz_Prob' 'Skeletonema' 'Steph_Melo'...
    'Thalassionema' 'Thalassiosira' 'Tropidoneis' 'Ciliates' 'Myrionecta'...
    'zooplankton_misc' 'Coccolithophore' 'Cryptophyte' 'cyst' 'Desmid'...
    'Dictyocha' 'Dolichospermum' 'FlagMix' 'NanoP_less10' 'Umbilicosphaera'...
    'Phaeocystis' 'Pyramimonas' 'small_misc'};

[~,ind_out] = intersect(class2use, class2get);
ind_out = sort(ind_out);

end