function [r] = import_RAI()

% Import data from RAI spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/afischer/Documents/UCSC_research/SCW_classifier/Jenny_Relative Abundance_180314.xls
%    Worksheet: JL SCW RAI
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/20 21:43:25

%% Import the data
[~, ~, raw] = xlsread('/Users/afischer/Documents/UCSC_research/SCW_classifier/Jenny_Relative Abundance_180314.xls','JL SCW RAI');
raw = raw(4:end,[5:7,10:12,14,22,24,33,35,56:57,61,76,81]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
dn = data(:,1)+695422;
AKA = data(:,2);
ALEX = data(:,3);
CER = data(:,4);
COCHLO = data(:,5);
DINO = data(:,6);
GYM = data(:,7);
PRORO = data(:,8);
PROTO = data(:,9);
CHAET = data(:,10);
COSC = data(:,11);
PN = data(:,12);
RHIZO = data(:,13);
THALSI = data(:,14);
dflag = data(:,15);
diat = data(:,16);

r(1).name='THALSI'; r(1).count=THALSI;
r(2).name='RHIZO'; r(2).count=RHIZO;
r(3).name='COSC'; r(3).count=COSC;
r(4).name='CHAET'; r(4).count=CHAET;
r(5).name='PN'; r(5).count=PN;
r(6).name='PROTO'; r(6).count=PROTO;
r(7).name='GYM'; r(7).count=GYM;
r(8).name='COCHLO'; r(8).count=COCHLO;
r(9).name='CER'; r(9).count=CER;
r(10).name='PRORO'; r(10).count=PRORO;
r(11).name='DINO'; r(11).count=DINO;
r(12).name='ALEX'; r(12).count=ALEX;
r(13).name='AKA'; r(13).count=AKA;
r(14).name='sum'; r(14).count=sum([r.count],2);
r(15).name='dflag'; r(15).rai=dflag./100;
r(16).name='diat'; r(16).rai=diat./100;

for i=1:13
    for j=1:length(r(14).count)
        r(i).rai(j)=r(i).count(j)./r(14).count(j);
    end
    r(i).rai=r(i).rai';
end

r(1).dn=dn;
r(2).dn=dn;
r(3).dn=dn;
r(4).dn=dn;
r(5).dn=dn;
r(6).dn=dn;
r(7).dn=dn;
r(8).dn=dn;
r(9).dn=dn;
r(10).dn=dn;
r(11).dn=dn;
r(12).dn=dn;
r(13).dn=dn;
r(14).dn=dn;
r(15).dn=dn;
r(16).dn=dn;

save('/Users/afischer/Documents/MATLAB/bloom-baby-bloom/SCW/Data/RAI_SCW','r');

end
