function [r] = import_RAI()
%% Import data from RAI spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/afischer/Documents/UCSC_research/SCW_classifier/SCW_RAI_180613.xls
%    Worksheet: SCW RAI_Leica
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/20 15:22:45

%% Import the data
[~, ~, raw] = xlsread('/Users/afischer/Documents/UCSC_research/SCW_classifier/SCW_RAI_180613.xls','SCW RAI_Leica');
raw = raw(4:end,5:65);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,33));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
dn = data(:,1)+695422;

r(1).name = 'AKA'; r(1).count = data(:,2);
r(2).name = 'ALEX'; r(2).count = data(:,3);
r(3).name = 'AMY'; r(3).count = data(:,4);
r(4).name = 'BOR'; r(4).count = data(:,5);
r(5).name = 'CER'; r(5).count = data(:,6);
r(6).name = 'COCHLO'; r(6).count = data(:,7);
r(7).name = 'DINO'; r(7).count = data(:,8);
r(8).name = 'GONY'; r(8).count = data(:,9);
r(9).name = 'GYM'; r(9).count = data(:,10);
r(10).name = 'GYR'; r(10).count = data(:,11);
r(11).name = 'HET'; r(11).count = data(:,12);
r(12).name = 'LING'; r(12).count = data(:,13);
r(13).name = 'NOCT'; r(13).count = data(:,14);
r(14).name = 'OXYPH'; r(14).count = data(:,15);
r(15).name = 'OXYTO'; r(15).count = data(:,16);
r(16).name = 'POLY'; r(16).count = data(:,17);
r(17).name = 'PRORO'; r(17).count = data(:,18);
r(18).name = 'PROCER'; r(18).count = data(:,19);
r(19).name = 'PROTO'; r(19).count = data(:,20);
r(20).name = 'PYRO'; r(20).count = data(:,21);
r(21).name = 'SCRIP'; r(21).count = data(:,22);
r(22).name = 'ACT'; r(22).count = data(:,23);
r(23).name = 'AMPHI'; r(23).count = data(:,24);
r(24).name = 'ASTNEL'; r(24).count = data(:,25);
r(25).name = 'ASTROM'; r(25).count = data(:,26);
r(26).name = 'BACT'; r(26).count = data(:,27);
r(27).name = 'CERAU'; r(27).count = data(:,28);
r(28).name = 'CHAET'; r(28).count = data(:,29);
r(29).name = 'CORE'; r(29).count = data(:,30);
r(30).name = 'COSC'; r(30).count = data(:,31);
r(31).name = 'CYLIN'; r(31).count = data(:,32);
r(32).name = 'DETO'; r(32).count = data(:,33);
r(33).name = 'DITY'; r(33).count = data(:,34);
r(34).name = 'EUC'; r(34).count = data(:,35);
r(35).name = 'FRAG'; r(35).count = data(:,36);
r(36).name = 'GUIN'; r(36).count = data(:,37);
r(37).name = 'HEMI'; r(37).count = data(:,38);
r(38).name = 'LAUD'; r(38).count = data(:,39);
r(39).name = 'LEPTO'; r(39).count = data(:,40);
r(40).name = 'LICO'; r(40).count = data(:,41);
r(41).name = 'LIOL'; r(41).count = data(:,42);
r(42).name = 'LITH'; r(42).count = data(:,43);
r(43).name = 'MELO'; r(43).count = data(:,44);
r(44).name = 'NAV'; r(44).count = data(:,45);
r(45).name = 'NITZ'; r(45).count = data(:,46);
r(46).name = 'ODON'; r(46).count = data(:,47);
r(47).name = 'PARAL'; r(47).count = data(:,48);
r(48).name = 'PLEURO'; r(48).count = data(:,49);
r(49).name = 'PROB'; r(49).count = data(:,50);
r(50).name = 'PN'; r(50).count = data(:,51);
r(51).name = 'RHIZO'; r(51).count = data(:,52);
r(52).name = 'SKEL'; r(52).count = data(:,53);
r(53).name = 'STEPH'; r(53).count = data(:,54);
r(54).name = 'THALNE'; r(54).count = data(:,55);
r(55).name = 'THALSI'; r(55).count = data(:,56);
r(56).name = 'THALTH'; r(56).count = data(:,57);
r(57).name = 'TROP'; r(57).count = data(:,58);
r(58).name = 'DICT'; r(58).count = data(:,59);
r(59).name = 'PHAEO'; r(59).count = data(:,60);
%r(60).name = 'fx_dino'; r(60).count = data(:,84);
%r(61).name = 'fx_diat'; r(61).count = data(:,end);

total=sum([r.count],2);

dinoflagellate=ones(length(data),21);
for i=1:size(dinoflagellate,2)
    dinoflagellate(:,i)=r(i).count;
end

diatom=ones(length(data),36);
for i=1:size(diatom,2)
    diatom(:,i)=r(i+21).count;
end
 
r(60).name='dinoflagellate'; r(60).count=sum(dinoflagellate,2);
r(61).name='diatom'; r(61).count=sum(diatom,2);

%calculate RAI
for i=1:length(r)
    for j=1:length(total)
        r(i).rai(j)=r(i).count(j)./total(j);
    end
    r(i).rai=r(i).rai';
    r(i).dn=dn;
end

save('/Users/afischer/Documents/MATLAB/bloom-baby-bloom/SCW/Data/RAI_SCW','r');

end
